### ISSUE TITLE
关于设置代理池的问题

### ISSUE THREAD

**Issue by RicordL** [crazyprobe/netease_music_comments_spider#1]
我在网上搜了一些函数，最后实现成了：
if __name__ == '__main__':
    url = 'http://www.xicidaili.com/nn/'
    ip_list = get_ip_list(url)
    proxies = get_random_ip(ip_list)
    PROXY_API_URL = proxies
这个样子可以用吗？之前IP封了。

**Comment by RicordL** [comment]
我已经测试成功了，但是速度从原来本机的300条/秒的速度降低到了100。

**Comment by m4yfly** [comment]
不好意思刚看到，回复的太迟啦 ,但没法直接这么用的，在程序里PROXY_API_URL是用来获取新地址的API，每次从这个URL的Response中取新的代理（免费的代理确实可用性低的很呐）

**Comment by RicordL** [comment]
嗯，我已经没问题了，已经解决了。
